# Generated by Django 3.2.25 on 2025-11-16 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='met',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='met',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mets.region'),
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commandes', models.PositiveIntegerField(default=0)),
                ('chiffre_affaires', models.PositiveIntegerField(default=0)),
                ('met', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='mets.met')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='mets.region')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('total', models.PositiveIntegerField()),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('met', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='mets.met')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
